[package]
name = "wasm_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-wasm = "0.42"
ark-crypto-primitives = { path = "/home/sami/ark/crypto-primitives" }
ark-std = "^0.3.0"
ark-sponge = "^0.3.0"
ark-bls12-377 = { version = "^0.3.0", features = [ "curve", "r1cs" ] }
